pytrap: add TrapCtx::recvBulk() for reading list of records
This new method can be used to receive UniRec records on background and
append them into a list() as dictionaries. This list is returned and can
be easily converted into pandas DataFrame.

The built-in help is as follows:

```
recvBulk(...) method of pytrap.TrapCtx instance
    Receive sequence of records at once via TRAP interface.

    Args:
        urtempl (UnirecTemplate): Created UnirecTemplate with the template, it is updated internally when the format is changed.

        time (int): Timeout in seconds before interrupt of capture.

        count (int): Maximum number of messages to capture, infinite when -1 (Warning! This can consume much memory.).

        ifcidx (Optional[int]): Index of input IFC (default: 0).

    Returns:
        list(dict): Received data.

    Raises:
        TrapError: Bad index given.
```

Example of usage:

```
>>> import pytrap
>>> u = pytrap.UnirecTemplate("")
>>> c = pytrap.TrapCtx()
>>> c.init(["-i", "f:~/osquery.trapcap"], 1, 0)
>>> c.setRequiredFmt(0)
>>> l = list()
>>> while True:
...     d = c.recvBulk(urtempl=u, time=1, count=-1)
...     l.extend(d)
...     if not d:
...         break
...
>>> print(pytrap.pd.DataFrame(l))
              DST_IP          SRC_IP   BYTES  BYTES_REV  LINK_BIT_FIELD  ... OSQUERY_OS_PLATFORM OSQUERY_OS_PLATFORM_LIKE OSQUERY_PROGRAM_NAME OSQUERY_SYSTEM_HOSTNAME  OSQUERY_USERNAME
0     109.123.194.25   192.168.1.248     138         99               1  ...                rhel                     rhel                 mutt               localhost            cejkat
...              ...             ...     ...        ...             ...  ...                 ...                      ...                  ...                     ...               ...
2515   216.58.201.78   192.168.1.248  149153      64084               1  ...                rhel                     rhel              firefox               localhost            cejkat

[2516 rows x 28 columns]
>>> c.finalize()
>>>
```