Revert "Merge branch 'master' into python3" due to errors
* import fails in unirec_generate_fields_files.py
* in python 2.6.6 (old scientific linux) python_example.py fails:
   SyntaxError: unqualified exec is not allowed in function
   'CreateTemplate' it contains a nested function with free variables

This reverts commit f18868953f35d11ef315580806140c71af69c75b, reversing
changes made to 2547838fac66ba37289bee9eb6d579a53c16d5af.