pytrap: add read_nemea() returns pandas.DataFrame or list(dict)
The new method read_nemea() works as follows:

```
Read `nrows` records from NEMEA TRAP interface given by `ifc_spec` and convert then into Pandas DataFrame.

Args:
  ifc_spec (str): IFC specifier for TRAP input IFC, see https://nemea.liberouter.org/trap-ifcspec/
  nrows (int): Number of records, read until end of stream (zero size message) if -1.
  array (bool): Set output type to list of dictionary instead of pandas.DataFrame

Returns:
  pandas.DataFrame or list of dictionary: DataFrame if array is False, otherwise, list of dictionary

Raises:
  ModuleNotFoundError: When pandas is not installed.
```

The patch also adds UnirecTemplate::getDict() that converts the single
UniRec record into dict().

Example of use:

```
import pytrap

print(pytrap.read_nemea("f:~/osquery.trapcap"))

```